analytics: {}
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.320101
  lightness: 0.494932
  rhythmicContrast: 0.425338
  saturation: 0.5
cta: {}
layout_spectrum: 0.784628
name: Thatsagoodtaste
opengraph: {}
purpose: []
typography_spectrum: 0.49678
