name: Thatsagoodtaste
favicon: null
layout_spectrum: 0.11898409319110215
typography_spectrum: 0.3341519543901086
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5221836699638516
  lightness: 0.8354287897236645
  saturation: 0.7428285947535187
  rhythmicContrast: 0.4253385616466403
purpose: []
